<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bb8b70a6-ee28-42be-9492-6991a01cd27f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FastDrop.Application\FastDrop.Application.csproj" />
    <ProjectReference Include="..\FastDrop.Infrastructure\FastDrop.Infrastructure.csproj" />
  </ItemGroup>

</Project>
