// <auto-generated />
using System;
using FastDrop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FastDrop.Infrastructure.Migrations
{
    [DbContext(typeof(FastDropDbContext))]
    partial class FastDropDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FastDrop.Domain.Entities.ChunkMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("FileMetadataId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileMetadataId", "ChunkNumber")
                        .IsUnique();

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("FastDrop.Domain.Entities.FileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransferSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransferSessionId")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("FastDrop.Domain.Entities.TransferSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiverTokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SenderTokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.ToTable("TransferSessions");
                });

            modelBuilder.Entity("FastDrop.Domain.Entities.ChunkMetadata", b =>
                {
                    b.HasOne("FastDrop.Domain.Entities.FileMetadata", null)
                        .WithMany("Chunks")
                        .HasForeignKey("FileMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastDrop.Domain.Entities.FileMetadata", b =>
                {
                    b.HasOne("FastDrop.Domain.Entities.TransferSession", null)
                        .WithOne("File")
                        .HasForeignKey("FastDrop.Domain.Entities.FileMetadata", "TransferSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastDrop.Domain.Entities.FileMetadata", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("FastDrop.Domain.Entities.TransferSession", b =>
                {
                    b.Navigation("File")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
